default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000
  username: alex
  password: 123
  host: localhost
  port: 9490
  gssencmode: disable

development:
  <<: *default
  database: test_guru

test:
  <<: *default
  database: test_guru

production:
  <<: *default
  database: test_guru